# Generated by Django 5.2.8 on 2025-11-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_attempt_score_alter_attempt_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('term_def', '1. Нэр томъёо ба тодорхойлолт'), ('vehicle_class', '2. Механикжсан тээврийн хэрэгслийн ангилал'), ('driver_duty', '3. Жолоочийн үүрэг'), ('special_signal', '4. Тусгай дуут болон гэрлэн дохио ажиллуулсан тээврийн хэрэгслийн хөдөлгөөн'), ('road_sign', '5. Замын тэмдэг'), ('road_mark', '6. Замын тэмдэглэл'), ('traffic_signal', '7. Замын хөдөлгөөн зохицуулах дохио'), ('warning_signal', '8. Анхааруулах дохио ба таних тэмдэг'), ('start_turn', '9. Хөдөлгөөн эхлэх болон чиг өөрчлөх'), ('lane', '10. Тээврийн хэрэгсэл байрлан явах'), ('speed', '11. Тээврийн хэрэгслийн хурд'), ('overtake', '12. Гүйцэж түрүүлэх ба гүйцэх'), ('stop_parking', '13. Түр ба удаан зогсох'), ('intersection', '14. Уулзвар нэвтрэх'), ('pedestrian_crossing', '15. Явган хүний гарц нэвтрэх'), ('rail_crossing', '16. Төмөр замын гарам нэвтрэх'), ('lighting', '17. Гадна талын гэрэлтүүлэх хэрэгслийг хэрэглэх'), ('residential', '18. Хорооллын доторх хөдөлгөөн'), ('highway', '19. Тууш замын хөдөлгөөн'), ('towing', '20. Механикжсан тээврийн хэрэгслийг чирэх'), ('transport_people_goods', '21. Хүн ба ачаа тээвэрлэх'), ('vehicle_fault', '22. Тээврийн хэрэгслийн эвдрэл гэмтэл, техникийн зөрчил'), ('driving_theory', '23. Тээврийн хэрэгслийг аюулгүй жолоодох онол'), ('first_aid', '24. Эмнэлгийн анхны тусламж')], default='general', max_length=50),
        ),
    ]
